-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE ApplicationUser
(
  Id INT NOT NULL IDENTITY PRIMARY KEY,
  FirstName VARCHAR(255) NOT NULL,
  LastName VARCHAR(255) NOT NULL,
  IsAdmin bit NOT NULL,
  Archived bit NOT NULL,
  CreatedAt DATETIME NOT NULL default(CURRENT_TIMESTAMP),
  UpdatedAt DATETIME NULL,
  DeletedAt DATETIME NULL,
  Email VARCHAR(255) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  ImageString VARCHAR(255) NOT NULL,
);

-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE ToDo
(
  Id INT NOT NULL IDENTITY PRIMARY KEY,
  Title VARCHAR(255) NOT NULL,
  ImageString VARCHAR(255) NOT NULL,
  ContentToDo VARCHAR(255) NOT NULL,
  IsRead bit NOT NULL,
  Archived bit NOT NULL,
  CreatedAt DATETIME NOT NULL default(CURRENT_TIMESTAMP),
  UpdatedAt DATETIME NULL,
  DeletedAt DATETIME NULL,
  UserIdTask INT NOT NULL,
  UserId INT NOT NULL,
  FOREIGN KEY (UserId) REFERENCES ApplicationUser(Id)
);